server:
  port: 7001

#Eureka的配置
eureka:
  instance:
    hostname: localhost #服务端实例名字
  client:
    registerWithEureka: false # 表示是否想eureka注册中心注册自己
    fetchRegistry: false #如果是false表示自己为注册中心
    serviceUrl:  #监控页面
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/